language: php

sudo: false

cache:
    directories:
        - $HOME/.composer/cache

php:
  - 7.3
  - 7.4
  - 8.0

install:
  - travis_retry composer update --no-interaction --no-suggest --no-progress --prefer-stable
  - travis_retry wget -O /tmp/coveralls.phar https://github.com/satooshi/php-coveralls/releases/download/v1.0.1/coveralls.phar

script:
  - php vendor/bin/phpunit --coverage-clover tests/coverage.xml -c tests/phpunit.xml
  - php vendor/bin/parallel-lint -e php,phpt --exclude vendor .
  - php vendor/bin/phpcs --standard=ruleset.xml --encoding=utf-8 -sp KdybyCodingStandard/ tests/
  - php vendor/bin/phpstan analyse --ansi --no-progress

after_script:
  - php /tmp/coveralls.phar --verbose --config tests/.coveralls.yml || true

after_failure:
  - 'for i in $(find ./tests -name \*.actual); do echo "--- $i"; cat $i; echo; echo; done'
